### PR TITLE
Init

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves https://github.com/ubiquibot/kernel-logger/issues/1

- Supabase posting built in
- Configurable so that any level can be posted
- Initiated with the name of the plugin and it replaces `metadata.caller`
- it is built on top of https://github.com/ubiquity/ubiquibot-logger and stays in sync with it via a script and `npm-check-updates` 

Usage:

```ts
logger: new Logs(
      "info", // LogLevel
      "url",
      "key",
      "start-stop-command",
      ["info"] // LogLevel(s) to post on
    ),
```

QA:

image

### CODE REVIEW

**Comment by Keyrxng** [comment]
@0x4007 Should we start to brand things under `@ubiquity-os` for packages now?

**Comment by Keyrxng** [comment]
Will we need to make a new `npmjs` account or will it post under `@ubiquity-os` if that name isn't already taken?

**Comment by whilefoo** [comment]
Since this will be used both in kernel and plugins, wouldn't it make sense to just make it a part of [ubiquibot-logger](https://github.com/ubiquity/ubiquibot-logger)?

**Comment by Keyrxng** [comment]
> Since this will be used both in kernel and plugins, wouldn't it make sense to just make it a part of [ubiquibot-logger](https://github.com/ubiquity/ubiquibot-logger)?

The reason we removed Supabase etc from the logger originally was so that it wasn't so easily accessed in non-core plugins and was decoupled from posting comments and logs. The reason why we also avoid using `fatal` with that logger is because the intention behind fatal was that it would post to SB.

I thought about variations of adding it to [ubiquibot-logger](https://github.com/ubiquity/ubiquibot-logger) via a separate exported class/dir etc but felt that was undo-ing what we set out to do by removing Supabase in the first place.

I'm happy to add it into the logger if that's preferred though

**Comment by gentlementlegen** [comment]
I wonder if that would make more sense as @whilefoo said to include this directly in our current logger. I would imagine more like a `plugin` system within it that would improve its capabilities (like `octokit` does for example). We could supercharge the logger with more modules, for example a `supabase` one which would also take care of adding the logs to supabase. The advantages of this approach would be that users shouldn't worry about which package to chose for their logs, and the whole code logic would remain the same. We could add supabase logs to any project using the logger, with one line of code.

**Comment by Keyrxng** [comment]
For previous context
- https://github.com/ubiquity/ubiquibot-logger/issues/2
- https://github.com/ubiquity/ubiquibot-logger/pull/4

---

> users shouldn't worry about which package to chose for their logs

Only core plugins and the kernel should post to supabase, so the users would have been just us but I hear what you are saying.

So adding posting capabilities back into https://github.com/ubiquity/ubiquibot-logger:

1. What key is required to post to our logs table, `service` or `anon`?
2. What levels should be posted on, just fatal as originally intended or should it be configurable like this PR?
3. Should the logger receive a `client` or should it receive `key` and `url` and init a client?
 
> whole code logic would remain the same

I'd expect that for each `plugin` we'd need to add an intercept on each log method or add function decorators. so would I wrap https://github.com/ubiquity/ubiquibot-logger in a Proxy like I have done here and re-export it or would the posting logic be added directly to level(s) which should post (i.e fatal) or via a service class and call to from each log?

`plugin` system so like a Telegram integration as well which is planned also how does that look to you?

The logger accepts various groups of init values and then inits the underlying packages and we intercept calls to log functions and post?

It was decided that the logger would not post comments anymore and each plugin would handle that. Is that a `plugin` which would be added for example?

**Comment by gentlementlegen** [comment]
The scenario in my head was something like:
I want `command-start-stop` to log its own logs into its own Supabase instance, to not clutter the main Supabase instance. If I am already using `ubiquibot-logger`, it is as straightforward as adding the Supabase-logger plugin to ubiquibot-logger, and I can start posting to supabase (provided I set up the SUPABASE_KEY, id, and so on). That would be very helpful and make upgrading our plugins very easy.

**Comment by Keyrxng** [comment]
Okay this sounds to me like `Supabase-logger plugin` is an NPM package and you just installed the package and now `ubiquibot-logger` can post to your `key` and `url` Supabase instance, is that right?

**Comment by whilefoo** [comment]
> Okay this sounds to me like `Supabase-logger plugin` is an NPM package and you just installed the package and now `ubiquibot-logger` can post to your `key` and `url` Supabase instance, is that right?

I don't see the value in having the plugin as a separate package, if you do that like in this PR you have to keep the versions in sync.
We could just use a boolean when initializing the logger to enable Supabase or like in this PR make a new Logger class that extends the current one but that would mean using Proxy which just complicates things. 
You can just provide supabase url and key and which table to add logs to (that could be the main DB of the plugin or a separate)

> 1. What key is required to post to our logs table, `service` or `anon`?

I believe you have to use `service` key because it has write permission, but `anon` could be possible if you add write permissions to the specific table but I don't see why that would be better.

> * What levels should be posted on, just fatal as originally intended or should it be configurable like this PR?

It can be configurable



> 3\. Should the logger receive a `client` or should it receive `key` and `url` and init a client?
> 
> >

I would say only key and url

**Comment by Keyrxng** [comment]
> I believe you have to use service key because it has write permission

So each plugin that uses these features will need to either spin up a dedicated db or uses the main DB service key. They'd need to pass it in either via `env` (secrets) or `settings` (org config) and it would need to be labeled as the `service_key` so that it is not used by mistake where the `anon` key should be used.

If it's `env` we control it and that makes sense for core plugins. For non-core plugins that would mean that the data is being stored in the plugin devs DB not the partner's and I'd assume the partner would want the storage vs the plugin author? Either way this should be well documented so it's clear to developer and partner 

If it's `settings` the partner has the ability to change the storage instance even for core plugins.

So which is the best way to handle this going forward?

If we allow the `anon` key to post then anyone can spam our official db so that's a non-starter.

**Comment by whilefoo** [comment]
> If it's `env` we control it and that makes sense for core plugins. For non-core plugins that would mean that the data is being stored in the plugin devs DB not the partner's and I'd assume the partner would want the storage vs the plugin author, plus the fact, if all partner's user bases are separate entities then the plugin dev will have the storage for all partners, if they decide to delete their DB or whatever then the plugin(s) stop working. Either way this should be well documented so it's clear to developer and partner

We've never discussed this but I thought that non-core plugin will host their own DB because it would be burdensome for partners to host the plugins themselves. 


> What reason do I have as a plugin developer to host a database and potentially have to incur costs to have partners use my plugins?

If I remember correctly there was a plan that each plugin would take a "fee" either per invocation or monthly subscription, so it's in plugin developer's best interest to host it, otherwise if everybody just self-hosts their plugin, how will they monetize it?

**Comment by 0x4007** [comment]
My vision is to have default data storage + UbiquityOS SDK help for git based JSON storage. This is so that there are no external dependencies (like a Supabase) to set up for storage. Everything "just works."

Because this seems to be a few months out at least, we can use something like Supabase, but yes, each plugin developer would have to set up their own databases. 

Yes the plugin developer will host it, and we will need to make the "install plugin" wizard as simple as possible so that partners would do that as the default flow. Even if the code is open sourced, if its convenient to set up, MOST partners will not mod the code to remove the fees and set up self hosting.

**Pull request closed without merging**
